sudo: required
dist: trusty

services:
- docker

script:
- docker build -t theia-build .

after_script:
- docker images

before_deploy:
- docker tag theia-build $DOCKER_USERNAME/theia-build

deploy:
  provider: script
  skip_cleanup: true
  script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  on:
    branch: master

# helpful links
# https://medium.com/mobileforgood/patterns-for-continuous-integration-with-docker-on-travis-ci-71857fff14c5

